/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinkedListJNI */

#ifndef _Included_LinkedListJNI
#define _Included_LinkedListJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LinkedListJNI
 * Method:    nativeHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LinkedListJNI_nativeHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
